blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/usarral/typescript-cli-template/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/usarral/typescript-cli-template#readme
    about: Read the project documentation
